_wandb:
    value:
        cli_version: 0.19.10
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 80
                - 105
                - 106
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 80
                - 105
                - 106
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.10
            "6": 4.27.4
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
